#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""把 page/index.html 内嵌成 src/index_html.h，供 MOINK_EMBED_PAGE=1 时使用。

输出符号：
    static const unsigned char index_html[] = { ... };
    static const unsigned int  index_html_len  = NNN;

字节原样嵌入（UTF-8），不转义字符串，避免 C 字符串字面量的长度上限。
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(ROOT, "page", "index.html")
DST = os.path.join(ROOT, "src", "index_html.h")


def main():
    data = open(SRC, "rb").read()
    n = len(data)

    lines = []
    lines.append("/* auto-generated by tools/make_index_header.py - do not edit */")
    lines.append("static const unsigned char index_html[] = {")
    for i in range(0, n, 16):
        chunk = data[i:i + 16]
        lines.append("    " + ",".join("0x%02x" % b for b in chunk) + ",")
    lines.append("};")
    lines.append("static const unsigned int index_html_len = %d;" % n)
    lines.append("")

    open(DST, "w", encoding="ascii").write("\n".join(lines))
    print("wrote %s (%d bytes -> %s)" % (SRC, n, DST))


if __name__ == "__main__":
    main()
